import { type Blueprint, type Migration, Schema } from '@gravito/atlas'

/**
 * Create Users Table Migration
 *
 * Generated by @gravito/fortify
 */
export default class CreateUsersTable implements Migration {
  /**
   * Run the migration
   */
  async up(): Promise<void> {
    await Schema.create('users', (table: Blueprint) => {
      table.id()
      table.string('name')
      table.string('email').unique()
      table.timestamp('email_verified_at').nullable()
      table.string('password')
      table.string('remember_token', 100).nullable()
      table.timestamps()
    })
  }

  /**
   * Reverse the migration
   */
  async down(): Promise<void> {
    await Schema.dropIfExists('users')
  }
}
