import { type Blueprint, type Migration, Schema } from '@gravito/atlas'

/**
 * Create Password Reset Tokens Table Migration
 *
 * Generated by @gravito/fortify
 */
export default class CreatePasswordResetTokensTable implements Migration {
  /**
   * Run the migration
   */
  async up(): Promise<void> {
    await Schema.create('password_reset_tokens', (table: Blueprint) => {
      table.string('email').primary()
      table.string('token')
      table.timestamp('created_at').nullable()
    })
  }

  /**
   * Reverse the migration
   */
  async down(): Promise<void> {
    await Schema.dropIfExists('password_reset_tokens')
  }
}
