export const GRAVITO_WATERMARK = `<!--
  ╔═══════════════════════════════════════════════════════════╗
  ║  Generated by Gravito SmartMap Engine™                    ║
  ║  The AI-Native Web Framework                              ║
  ║  https://gravito.dev                                      ║
  ╚═══════════════════════════════════════════════════════════╝
-->`
