import { spawn, write, file } from 'bun'

console.log('Building @gravito/luminosity-cli...')

// Clean dist
await Bun.$`rm -rf dist`

// Use tsup for main entry (esm, cjs)
const tsupMain = spawn(
  [
    'npx',
    'tsup',
    'src/index.ts',
    '--format',
    'esm,cjs',
    '--dts',
    '--external',
    '@gravito/luminosity,commander,picocolors',
    '--outDir',
    'dist',
  ],
  {
    stdout: 'inherit',
    stderr: 'inherit',
  }
)

const tsupMainCode = await tsupMain.exited
if (tsupMainCode !== 0) {
  console.error('❌ tsup main build failed')
  process.exit(1)
}

// Use tsup for CLI binary (esm with shebang)
const tsupCli = spawn(
  [
    'npx',
    'tsup',
    'bin/gravito-seo.ts',
    '--format',
    'esm',
    '--external',
    '@gravito/luminosity,commander,picocolors',
    '--outDir',
    'dist/bin',
    '--no-dts', // types already generated by main build
  ],
  {
    stdout: 'inherit',
    stderr: 'inherit',
  }
)

const tsupCliCode = await tsupCli.exited
if (tsupCliCode !== 0) {
  console.error('❌ tsup CLI build failed')
  process.exit(1)
}

// Add shebang to CLI binary and make executable
const cliFile = './dist/bin/gravito-seo.js'
const content = await file(cliFile).text()
const withShebang = content.startsWith('#!/usr/bin/env node')
  ? content
  : `#!/usr/bin/env node\n${content}`
await write(cliFile, withShebang)
await Bun.spawn(['chmod', '+x', cliFile]).exited

console.log('✅ Build completed')
process.exit(0)