import type { ImageOptions } from '../ImageService'
import { ImageService } from '../ImageService'
import React from 'react'

/**
 * Props for the `Image` component.
 */
export interface ImageProps {
  src: string
  width?: number
  height?: number
  alt: string
  loading?: 'lazy' | 'eager'
  sizes?: string
  srcset?: boolean | number[]
  className?: string
  style?: string
  decoding?: 'async' | 'auto' | 'sync'
  fetchpriority?: 'high' | 'low' | 'auto'
}

/**
 * Image component (server-rendered only).
 *
 * No client-side dependencies: all logic runs on the server.
 * Uses `ImageService` to generate an optimized `<img>` tag.
 *
 * @example
 * ```tsx
 * <Image
 *   src="/static/hero.jpg"
 *   width={1920}
 *   height={1080}
 *   alt="Hero"
 *   loading="eager"
 * />
 * ```
 */
export function Image(props: ImageProps): React.JSX.Element {
  const imageService = new ImageService()

  // Convert React props to ImageOptions
  const options: ImageOptions = {
    src: props.src,
    alt: props.alt,
    width: props.width,
    height: props.height,
    loading: props.loading,
    sizes: props.sizes,
    srcset: props.srcset,
    class: props.className,
    style: props.style,
    decoding: props.decoding,
    fetchpriority: props.fetchpriority,
  }

  // Generate HTML
  const html = imageService.generateImageTag(options)

  // Use dangerouslySetInnerHTML to render the raw HTML string.
  // This is required because we need to output a full `<img>` tag.
  // In SSR, this is safe because all output is generated by ImageService.
  // biome-ignore lint/security/noDangerouslySetInnerHtml: output is generated by ImageService
  return <span dangerouslySetInnerHTML={{ __html: html }} />
}

// Default export
export default Image
